package pt.lsts.accl.systemlist;

import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.os.IBinder;
import android.util.Log;

import com.squareup.otto.Produce;
import com.squareup.otto.Subscribe;

import pt.lsts.accl.android.AcclActivity;
import pt.lsts.accl.android.AcclService;
import pt.lsts.accl.bus.AcclBus;
import pt.lsts.accl.event.EventMainSystemSelected;
import pt.lsts.accl.event.EventSystemConnected;
import pt.lsts.accl.event.EventSystemDisconnected;
import pt.lsts.accl.event.EventSystemVisible;
import pt.lsts.accl.sys.Sys;
import pt.lsts.imc.IMCMessage;
import pt.lsts.imc.PlanControlState;

/**
 *
 *
 * Created by jloureiro on 02-07-2015.
 */
public class AcclBusListenner extends AcclService {

    /**
     * Log the {@link AcclBus} messages.
     *
     * @param s The Message generated by {@link AcclBus}
     */
    @Subscribe
    public void on(String s){

        switch (s.charAt(0)){
            case 'E'://ERROR
                Log.e(TAG, s);
                break;
            case 'W'://Warning
                Log.w(TAG, s);
                break;
            case 'I'://Info
                Log.i(TAG, s);
                break;
            case 'D'://Debug
                Log.d(TAG, s);
                break;
            case 'V':// Verbose
            default:// none defined, print on Verbose
                Log.v(TAG, s);
                break;
        }
    }

}
